/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metas;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Augusto
 */
public class Linguagem_preferida extends javax.swing.JFrame {

    /**
     * Creates new form Linguagem_preferida
     */
    public Linguagem_preferida() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        // Agrupando Botões
        ButtonGroup opcoes_linguagem = new ButtonGroup();
        
        opcoes_linguagem.add(radio_php);
        opcoes_linguagem.add(radio_java);
        opcoes_linguagem.add(radio_python);
        opcoes_linguagem.add(radio_javascript);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radio_php = new javax.swing.JRadioButton();
        radio_java = new javax.swing.JRadioButton();
        radio_python = new javax.swing.JRadioButton();
        radio_javascript = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Qual sua linguagem favorita?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        radio_php.setBackground(new java.awt.Color(255, 255, 255));
        radio_php.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_php.setText("PHP");
        radio_php.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_php.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_phpActionPerformed(evt);
            }
        });

        radio_java.setBackground(new java.awt.Color(255, 255, 255));
        radio_java.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_java.setText("Java");
        radio_java.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_javaActionPerformed(evt);
            }
        });

        radio_python.setBackground(new java.awt.Color(255, 255, 255));
        radio_python.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_python.setText("Python");
        radio_python.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_python.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_pythonActionPerformed(evt);
            }
        });

        radio_javascript.setBackground(new java.awt.Color(255, 255, 255));
        radio_javascript.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        radio_javascript.setText("JavaScript");
        radio_javascript.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radio_javascript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_javascriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(radio_php)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_java)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_python)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_javascript)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_php)
                    .addComponent(radio_java)
                    .addComponent(radio_python)
                    .addComponent(radio_javascript))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_phpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_phpActionPerformed
        JOptionPane.showMessageDialog(null, "Aceitável...");
    }//GEN-LAST:event_radio_phpActionPerformed

    private void radio_javaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_javaActionPerformed
        JOptionPane.showMessageDialog(null, "Isso aí!");
    }//GEN-LAST:event_radio_javaActionPerformed

    private void radio_pythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_pythonActionPerformed
        JOptionPane.showMessageDialog(null, "Nutela...");
    }//GEN-LAST:event_radio_pythonActionPerformed

    private void radio_javascriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_javascriptActionPerformed
        JOptionPane.showMessageDialog(null, "Questionável, mas tudo bem");
    }//GEN-LAST:event_radio_javascriptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Linguagem_preferida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radio_java;
    private javax.swing.JRadioButton radio_javascript;
    private javax.swing.JRadioButton radio_php;
    private javax.swing.JRadioButton radio_python;
    // End of variables declaration//GEN-END:variables
}
