/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metas;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Augusto
 */
public class Linguagem_preferida extends javax.swing.JFrame {

    /**
     * Creates new form Linguagem_preferida
     */
    public Linguagem_preferida() {
        initComponents();
        
        // Agrupando Botões
        ButtonGroup opcoes_linguagem = new ButtonGroup();
        
        opcoes_linguagem.add(radio_php);
        opcoes_linguagem.add(radio_java);
        opcoes_linguagem.add(radio_python);
        opcoes_linguagem.add(radio_javascript);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JPanel();
        painel_cabecalho = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painel_opcoes = new javax.swing.JPanel();
        radio_php = new javax.swing.JRadioButton();
        radio_java = new javax.swing.JRadioButton();
        radio_python = new javax.swing.JRadioButton();
        radio_javascript = new javax.swing.JRadioButton();
        botao_enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel_cabecalho.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Qual sua linguagem favorita?");

        javax.swing.GroupLayout painel_cabecalhoLayout = new javax.swing.GroupLayout(painel_cabecalho);
        painel_cabecalho.setLayout(painel_cabecalhoLayout);
        painel_cabecalhoLayout.setHorizontalGroup(
            painel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
        painel_cabecalhoLayout.setVerticalGroup(
            painel_cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_cabecalhoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        painel_opcoes.setBackground(new java.awt.Color(255, 255, 255));

        radio_php.setBackground(new java.awt.Color(255, 255, 255));
        radio_php.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        radio_php.setText("PHP");
        radio_php.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        radio_java.setBackground(new java.awt.Color(255, 255, 255));
        radio_java.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        radio_java.setText("Java");
        radio_java.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        radio_python.setBackground(new java.awt.Color(255, 255, 255));
        radio_python.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        radio_python.setText("Python");
        radio_python.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        radio_javascript.setBackground(new java.awt.Color(255, 255, 255));
        radio_javascript.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        radio_javascript.setText("JavaScript");
        radio_javascript.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout painel_opcoesLayout = new javax.swing.GroupLayout(painel_opcoes);
        painel_opcoes.setLayout(painel_opcoesLayout);
        painel_opcoesLayout.setHorizontalGroup(
            painel_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_opcoesLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(radio_php)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_java)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_python)
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(radio_javascript)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        painel_opcoesLayout.setVerticalGroup(
            painel_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_opcoesLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(painel_opcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_php)
                    .addComponent(radio_java)
                    .addComponent(radio_python)
                    .addComponent(radio_javascript))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        botao_enviar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        botao_enviar.setText("Enviar");
        botao_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_enviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_principalLayout = new javax.swing.GroupLayout(painel_principal);
        painel_principal.setLayout(painel_principalLayout);
        painel_principalLayout.setHorizontalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_cabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painel_opcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_enviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_principalLayout.setVerticalGroup(
            painel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_principalLayout.createSequentialGroup()
                .addComponent(painel_cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(painel_opcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_enviarActionPerformed
        
        if (radio_php.isSelected()) {
            
            JOptionPane.showMessageDialog(this, "PHP é uma ótima linguagem para backend de sites!");
            
        } else if (radio_java.isSelected()) {
            
            JOptionPane.showMessageDialog(this, "Java é uma linguagem multiplataforma sensacional!");
            
        } else if (radio_python.isSelected()) {
            
            JOptionPane.showMessageDialog(this, "Python é uma boa linguagem para se iniciar na programação!");
            
        } else if (radio_javascript.isSelected()) {
            
            JOptionPane.showMessageDialog(this, "JavaScript é uma linguagem frontend, ela roda no seu navegador!");
            
        } else {
            
            JOptionPane.showMessageDialog(this, "Escolha uma linguagem!");
            
        }
        
    }//GEN-LAST:event_botao_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Linguagem_preferida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Linguagem_preferida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel painel_cabecalho;
    private javax.swing.JPanel painel_opcoes;
    private javax.swing.JPanel painel_principal;
    private javax.swing.JRadioButton radio_java;
    private javax.swing.JRadioButton radio_javascript;
    private javax.swing.JRadioButton radio_php;
    private javax.swing.JRadioButton radio_python;
    // End of variables declaration//GEN-END:variables
}
